name: Build and Deploy Jekyll Blog

on:
  schedule:
    - cron: '0 1 * * *' # daily at 1 AM UTC
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          python -m pip install --upgrade pip
          pip install transformers language_tool_python sentence-transformers jinja2

      - name: Run blog content generation script
        run: python generate_content.py

      - name: Build Jekyll site
        run: |
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
