name: Generate sitemap

on:
  push:
    branches: [ main ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate sitemap for officialadamrivers.github.io

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://officialadamrivers.github.io/

    - name: Commit and push sitemap.xml if changed
      run: |
        if [[ `git status --porcelain sitemap.xml` ]]; then
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add sitemap.xml
          git commit -m "Automated sitemap update"
          git push
        fi
